AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Lambda Layer providing sharp with HEIC support

Metadata:
  AWS::ServerlessRepo::Application:
    Name: sharp-heic
    Description: Lambda Layer providing sharp with HEIC support
    Author: Andreas Zoellner
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['sharp', 'heic', 'layer']
    HomePageUrl: https://github.com/zoellner/sharp-heic-lambda-layer
    SemanticVersion: 1.0.3
    SourceCodeUrl: https://github.com/zoellner/sharp-heic-lambda-layer

Globals:
  Function:
    Timeout: 5
    Runtime: nodejs12.x

Parameters:
  DeployTest:
    Default: false
    Description: Choose whether to deploy the test function or not
    Type: String
    AllowedValues:
      - true
      - false

Conditions:
  IsDeployTest: !Equals [ !Ref DeployTest, true ]

Resources:
  SharpHEICLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: sharp-heic
      Description: Sharp Layer with HEIC Support
      ContentUri: ./layer/
      CompatibleRuntimes:
        - nodejs12.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  SharpHEICLayerPermission:
    Type: AWS::Lambda::LayerVersionPermission
    Properties:
      Action: lambda:GetLayerVersion
      LayerVersionArn: !Ref SharpHEICLayer
      Principal: '*'

Outputs:
  LayerArn:
    Value: !Ref SharpHEICLayer
    Description: ARN of the Sharp HEIC Lambda Layer
